-- Table: dumped_queries

CREATE TABLE IF NOT EXISTS dumped_queries
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    n8n_id text COLLATE pg_catalog."default",
    sender_email text COLLATE pg_catalog."default" NOT NULL,
    sender_name text COLLATE pg_catalog."default",
    subject text COLLATE pg_catalog."default",
    body text COLLATE pg_catalog."default",
    failure_reason text COLLATE pg_catalog."default",
    ai_extracted_data jsonb,
    status text COLLATE pg_catalog."default" DEFAULT 'OPEN'::text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT dumped_queries_pkey PRIMARY KEY (id)
);

-- Index for status filtering
CREATE INDEX IF NOT EXISTS idx_dumped_queries_status
    ON dumped_queries USING btree
    (status COLLATE pg_catalog."default" ASC NULLS LAST);

-- Index for sender email search
CREATE INDEX IF NOT EXISTS idx_dumped_queries_sender
    ON dumped_queries USING btree
    (sender_email COLLATE pg_catalog."default" ASC NULLS LAST);
